spring:
  application:
    name: api
  datasource:
    url: jdbc:h2:mem:my-database
    driver-class-name: org.h2.Driver
    username: teste-dev
    password: dev@password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api